name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./BHYT_BE  # Specify the correct path to your main project
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./BHYT_BE  # Specify the correct path to your main project
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./BHYT_BE.Test  # Specify the correct path to your test project
